---
- name: Base Server Setup
  hosts: prod
  become: true
  tasks:
    - name: Ensure hostname is correct
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Update /etc/hosts with correct hostname
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: "127.0.1.1 {{ inventory_hostname }}"
